# Generated by Django 4.2.3 on 2023-08-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_client_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ("name",)},
        ),
    ]
